<?php
// module/Album/view/album/album/add.phtml:
$title = 'Add Product';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('inventry', array('action' =>'add')));
$form->prepare();
echo $this->form()->openTag($form);
echo $this->formHidden($form->get('product_id'));
echo $this->formRow($form->get('product_name'));
echo $this->formRow($form->get('product_description'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();





