<?php

    $title = "Edit Product";
    $this->headTitle($title);
?>

<h1><?php echo $this->escapeHtml($title); ?> </h1>

<?php
    $form = $this->form;
    $form->setAttribute('action', $this->url('inventry', $this->url(
        'inventry',array(
            'action' => 'edit',
            'id' => $this->id,
        )
         )));
    $form->prepare();

    echo $this->form()->openTag($form);
    echo $this->formHidden($form->get('product_id'));
    echo $this->formRow($form->get('product_name'));
    echo $this->formRow($form->get('product_description'));
    echo $this->formSubmit($form->get('submit'));
    echo $this->form()->closeTag();

